### ISSUE TITLE
Use libswt in android,It seems not work well

### ISSUE THREAD

**Issue by giskook** [talonvoice/libswt#1]
Hi,
I use the libswt in my android app,But It do not work well, My input image is RGBA format.It takes 4 bytes.I set the ccv_dense_matrix_new(rows, cols, CCV_8U | CCV_C4 | CCV_NO_DATA_ALLOC, (void *)data);But it crashed.I don't know weather or not I set the property right.Could you help me?
Thanks in advance,
zhangkai

**Comment by lunixbochs** [comment]
Oops, I didn't get a notification for this issue.

You should follow the example and convert your image to grayscale first, pixels is e.g. Gray8:
```
swt_array *words = swt_detect(pixels, width, height, NULL);
if (words) {
    for (int i = 0; i < swt_len(words); i++) {
        swt_rect *rect = swt_get(words, i);
        printf("%d %d %d %d\n", rect->x, rect->y, rect->width, rect->height);
    }
    swt_free(words);
}
```

**Comment by giskook** [comment]
@lunixbochs Thank you, yes I convert my image then it worked perfectly :)
